networks:
  network-iproact:
    external: true

volumes:
  postgres:

secrets:
  IPROACT_POSTGRES_DB:
    external: true
  IPROACT_POSTGRES_USER:
    external: true
  IPROACT_POSTGRES_PASSWORD:
    external: true
  IPROACT_POSTGRES_URL:
    external: true
  IPROACT:
    external: true

services:
  dozzle:
    deploy:
      restart_policy:
        condition: any
      update_config:
        order: start-first
        failure_action: rollback
    image: amir20/dozzle
    networks:
      - network-iproact
    environment:
      - DOZZLE_NO_ANALYTICS=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - '8080:8080'
    healthcheck:
      start_period: 10s
      start_interval: 1s
      test: ['CMD', '/dozzle', 'healthcheck']
      interval: 10s
      timeout: 5s
      retries: 2

  postgres:
    deploy:
      restart_policy:
        condition: any
      update_config:
        order: start-first
        failure_action: rollback
    image: image-iproact-postgres
    networks:
      - network-iproact
    secrets:
      - IPROACT_POSTGRES_DB
      - IPROACT_POSTGRES_USER
      - IPROACT_POSTGRES_PASSWORD
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB_FILE: /run/secrets/IPROACT_POSTGRES_DB
      POSTGRES_USER_FILE: /run/secrets/IPROACT_POSTGRES_USER
      POSTGRES_PASSWORD_FILE: /run/secrets/IPROACT_POSTGRES_PASSWORD
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      start_period: 10s
      start_interval: 1s
      test:
        [
          'CMD-SHELL',
          'pg_isready -U $$(cat /run/secrets/IPROACT_POSTGRES_USER) -d $$(cat /run/secrets/IPROACT_POSTGRES_DB)',
        ]
      interval: 10s
      timeout: 5s
      retries: 2

  pgweb:
    deploy:
      restart_policy:
        condition: any
      update_config:
        order: start-first
        failure_action: rollback
    image: sosedoff/pgweb
    networks:
      - network-iproact
    secrets:
      - IPROACT_POSTGRES_URL
    entrypoint: ['/bin/sh']
    command:
      - -c
      - 'pgweb --url "$$(cat /run/secrets/IPROACT_POSTGRES_URL)?sslmode=disable" --bind 0.0.0.0 --listen 8081'
    ports:
      - '8081:8081'
    healthcheck:
      start_period: 10s
      start_interval: 1s
      test: ['CMD', 'nc', '-vz', '127.0.0.1', '8081']
      interval: 10s
      timeout: 5s
      retries: 2

  nextjs:
    deploy:
      restart_policy:
        condition: any
      update_config:
        order: start-first
        failure_action: rollback
    image: image-iproact-nextjs
    networks:
      - network-iproact
    secrets:
      - IPROACT_POSTGRES_URL
      - IPROACT
    ports:
      - '80:3000'
    healthcheck:
      start_period: 10s
      start_interval: 1s
      test:
        [
          'CMD-SHELL',
          'curl -f http://localhost:3000/api/health | grep ok || exit 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 2
